/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.
    
Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, SmplDeviceCreateDevice)
#endif


NTSTATUS
SmplDeviceCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDF_PNPPOWER_EVENT_CALLBACKS PnpPowerEventCallbacks;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);
    deviceAttributes.SynchronizationScope = WdfSynchronizationScopeQueue;

    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&PnpPowerEventCallbacks);
    PnpPowerEventCallbacks.EvtDevicePrepareHardware = SmplDeviceEvtPrepareHardware;
    PnpPowerEventCallbacks.EvtDeviceReleaseHardware = SmplDeviceEvtReleaseHardware;
    PnpPowerEventCallbacks.EvtDeviceD0Entry = SmplDeviceEvtD0Entry;
    PnpPowerEventCallbacks.EvtDeviceD0Exit = SmplDeviceEvtD0Exit;
    WdfDeviceInitSetPnpPowerEventCallbacks( DeviceInit, &PnpPowerEventCallbacks);

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);
    if (NT_SUCCESS(status)) 
    {   //
        // Get the device context and initialize it. DeviceGetContext is an
        // inline function generated by WDF_DECLARE_CONTEXT_TYPE macro in the
        // device.h header file. This function will do the type checking and return
        // the device context. If you pass a wrong object  handle
        // it will return NULL and assert if run under framework verifier mode.
        //
        deviceContext = DeviceGetContext(device);

        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(device,
                                                &GUID_DEVINTERFACE_SMPLDEVICE,
                                                NULL);
        if (NT_SUCCESS(status)) 
        {   //
            // Initialize the I/O Package and any Queues
            //
            status = SmplDeviceQueueInitialize(device);
        }

        if (NT_SUCCESS(status)) {
            WDF_DEVICE_POWER_POLICY_IDLE_SETTINGS PowerPolicyIdleSettings;
            WDF_DEVICE_POWER_POLICY_IDLE_SETTINGS_INIT(&PowerPolicyIdleSettings, IdleCannotWakeFromS0);
            PowerPolicyIdleSettings.IdleTimeoutType = SystemManagedIdleTimeout;

            status = WdfDeviceAssignS0IdleSettings(device, &PowerPolicyIdleSettings);
            if (!NT_SUCCESS(status)) 
            {
                DbgPrintEx(DPFLTR_IHVDRIVER_ID, 1234,"WdfDeviceAssignS0IdleSettings failed! 0x%x\n", status);
            }
        }

        if (NT_SUCCESS(status)) {
            SmplPoFxSingleComponentInitialize(device);
        }

        if (NT_SUCCESS(status)) 
        {
            WDFINTERRUPT Interrupt;
            WDF_INTERRUPT_CONFIG Configuration;
            WDF_INTERRUPT_CONFIG_INIT(&Configuration, SmplInterruptEvtIsr, SmplInterruptEvtDpc);
            Configuration.EvtInterruptEnable = SmplInterruptEvtEnable;
            Configuration.EvtInterruptDisable = SmplInterruptEvtDisable;
            status = WdfInterruptCreate(device,
                                        &Configuration,
                                        WDF_NO_OBJECT_ATTRIBUTES,
                                        &Interrupt);
            if (!NT_SUCCESS(status)) 
            {
                DbgPrintEx(DPFLTR_IHVDRIVER_ID, 1234, "WdfInterruptCreate failed! 0x%x\n", status);
            }
        }

    }

    return status;
}

///////////////////////////////////////////////////////////////////////////////
// Plug'n'Play callback preparing hardware.
///////////////////////////////////////////////////////////////////////////////
NTSTATUS SmplDeviceEvtPrepareHardware(
  __in  WDFDEVICE Device,
  __in  WDFCMRESLIST ResourcesRaw,
  __in  WDFCMRESLIST ResourcesTranslated
)
{
    DbgPrintEx(DPFLTR_IHVDRIVER_ID, 1234, "SmplDeviceEvtPrepareHardware\n");
    SmplDeviceHwResourcesGet(Device, ResourcesTranslated);
    return STATUS_SUCCESS;

} // end SmplDeviceEvtPrepareHardware

///////////////////////////////////////////////////////////////////////////////
// Plug'n'Play callback releasing hardware.
///////////////////////////////////////////////////////////////////////////////
NTSTATUS SmplDeviceEvtReleaseHardware(
  __in  WDFDEVICE Device,
  __in  WDFCMRESLIST ResourcesTranslated
)
{
    DbgPrintEx(DPFLTR_IHVDRIVER_ID, 1234, "SmplDeviceEvtReleaseHardware\n");
    return STATUS_SUCCESS;

} // end SmplDeviceEvtReleaseHardware

///////////////////////////////////////////////////////////////////////////////
// Power callback entering D0 state.
///////////////////////////////////////////////////////////////////////////////
NTSTATUS SmplDeviceEvtD0Entry(
  __in  WDFDEVICE Device,
  __in  WDF_POWER_DEVICE_STATE PreviousState
)
{
    PDEVICE_CONTEXT pDeviceContext = DeviceGetContext(Device);
    DbgPrintEx(DPFLTR_IHVDRIVER_ID, 1234, "SmplDeviceEvtD0Entry PreviousState:%d\n", PreviousState);
    Hw8250Init(pDeviceContext->pPortAddress, 1200, 7, 1, 0);
    return STATUS_SUCCESS;

} // end SmplDeviceEvtD0Entry

///////////////////////////////////////////////////////////////////////////////
// Power callback exiting D0 state.
///////////////////////////////////////////////////////////////////////////////
NTSTATUS SmplDeviceEvtD0Exit(
  __in  WDFDEVICE Device,
  __in  WDF_POWER_DEVICE_STATE TargetState
)
{
    DbgPrintEx(DPFLTR_IHVDRIVER_ID, 1234, "SmplDeviceEvtD0Exit TargetState:%d\n", TargetState);
    return STATUS_SUCCESS;

} // end SmplDeviceEvtD0Exit

///////////////////////////////////////////////////////////////////////////////
// SmplDeviceEvtWdmPostPoFxRegisterDevice
// KMDF calls this routine after it has registered with the Power Framework
// and supplies the registration handle that driver can use directly.
///////////////////////////////////////////////////////////////////////////////
NTSTATUS
SmplDeviceEvtWdmPostPoFxRegisterDevice(
    _In_ WDFDEVICE Device,
    _In_ POHANDLE PoHandle
    )
{
    DEVICE_CONTEXT *pDeviceContext = DeviceGetContext(Device);

    pDeviceContext->PoHandle = PoHandle;

    //
    // Set latency and residency hints so that the power framework chooses lower
    // powered F-states when we are idle.
    // The values used here are for illustration purposes only. The driver 
    // should use values that are appropriate for its device.
    //
    PoFxSetComponentLatency(PoHandle, 0, (WDF_ABS_TIMEOUT_IN_MS(DEEPEST_FSTATE_LATENCY_IN_MS) + 1));
    PoFxSetComponentResidency(PoHandle, 0, (WDF_ABS_TIMEOUT_IN_SEC(DEEPEST_FSTATE_RESIDENCY_IN_SEC) + 1));
    return STATUS_SUCCESS;

} // end SmplDeviceEvtWdmPostPoFxRegisterDevice

